#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "${SCRIPT_DIR}/lib.sh"

parse_common_args "$@"
load_env_file

if [ "${DRY_RUN}" != "true" ]; then
  require_fab
fi
require_fab_auth
if [ -z "${FABRIC_WORKSPACE_ID:-}" ] && [ "${DRY_RUN}" = "true" ]; then
  FABRIC_WORKSPACE_ID="{FABRIC_WORKSPACE_ID}"
else
  require_env FABRIC_WORKSPACE_ID
fi

timestamp="$(date -u '+%Y%m%dT%H%M%SZ')"
EXPORT_DIR="${EXPORT_DIR:-${FABRIC_DIR}/exports/${timestamp}}"

if [ "${DRY_RUN}" = "true" ]; then
  info "Would create export directory: ${EXPORT_DIR}"
  run_fab_api get "/v1/workspaces/${FABRIC_WORKSPACE_ID}"
  run_fab_api get "/v1/workspaces/${FABRIC_WORKSPACE_ID}/items"
  for item_id in \
    "${FABRIC_EVENTSTREAM_ID:-}" \
    "${FABRIC_EVENTHOUSE_ID:-}" \
    "${FABRIC_KQL_DATABASE_ID:-}" \
    "${FABRIC_DASHBOARD_ID:-}" \
    "${FABRIC_REFLEX_ID:-}" \
    "${FABRIC_DATA_AGENT_ID:-}"; do
    if [ -n "${item_id}" ]; then
      run_fab_api post "/v1/workspaces/${FABRIC_WORKSPACE_ID}/items/${item_id}/getDefinition"
    fi
  done
  exit 0
fi

mkdir -p "${EXPORT_DIR}"
info "Exporting workspace metadata to ${EXPORT_DIR}"
run_fab_api get "/v1/workspaces/${FABRIC_WORKSPACE_ID}" > "${EXPORT_DIR}/workspace.json"
run_fab_api get "/v1/workspaces/${FABRIC_WORKSPACE_ID}/items" > "${EXPORT_DIR}/items.json"

export_definition_if_set() {
  local label="$1"
  local item_id="$2"

  if [ -z "${item_id}" ]; then
    return 0
  fi

  info "Exporting ${label} definition (${item_id})"
  run_fab_api post "/v1/workspaces/${FABRIC_WORKSPACE_ID}/items/${item_id}/getDefinition" \
    > "${EXPORT_DIR}/${label}-definition.json"
}

export_definition_if_set "eventstream" "${FABRIC_EVENTSTREAM_ID:-}"
export_definition_if_set "eventhouse" "${FABRIC_EVENTHOUSE_ID:-}"
export_definition_if_set "kql-database" "${FABRIC_KQL_DATABASE_ID:-}"
export_definition_if_set "dashboard" "${FABRIC_DASHBOARD_ID:-}"
export_definition_if_set "reflex" "${FABRIC_REFLEX_ID:-}"
export_definition_if_set "data-agent" "${FABRIC_DATA_AGENT_ID:-}"

cat > "${EXPORT_DIR}/README.txt" <<EOF
Generated by fabric/scripts/export-items.sh at ${timestamp}.

Review before committing. Do not commit secrets or tenant-sensitive definitions.
Use items.json to look up Fabric item IDs for fabric/config/grizl.fabric.env.
EOF

ok "Fabric export written to ${EXPORT_DIR}"
